Name: Product
Host: 0.0.0.0
Port: 8001


Auth:
  AccessSecret: uOvKLmVfztaXGpNYd4Z0I1SiT7MweJhl
  AccessExpire: 86400


ProductRpc:
  App: productapi
  Token: 6jKNZbEpYGeUMAifz10gOnmoty3TV  # Token 值
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: product.rpc


AuthRpc:
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: auth.rpc