// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type Address struct {
	StreetAddress string `json:"street_address"`
	City          string `json:"city"`
	State         string `json:"state"`
	Country       string `json:"country"`
	ZipCode       int32  `json:"zip_code"`
}

type CartItem struct {
	ProductId uint32 `json:"product_id"`
	Quantity  int32  `json:"quantity"`
}

type ListOrderRequest struct {
}

type ListOrderResponse struct {
	Orders []Order `json:"orders"`
}

type Order struct {
	OrderItems   []OrderItem `json:"order_items"`
	OrderId      string      `json:"order_id"`
	UserId       uint32      `json:"user_id"`
	UserCurrency string      `json:"user_currency"`
	UserAddress  Address     `json:"user_address"`
	Email        string      `json:"email"`
	CreateAt     string      `json:"create_at"`
}

type OrderItem struct {
	Item CartItem `json:"item"`
	Cost float64  `json:"cost"`
}

type OrderResult struct {
	OrderId string `json:"order_id"`
}

type PlaceOrderRequest struct {
	UserCurrency string      `json:"user_currency"`
	UserAddress  Address     `json:"user_address"`
	Email        string      `json:"email"`
	OrderItems   []OrderItem `json:"order_items"`
}

type PlaceOrderResponse struct {
	Order OrderResult `json:"order"`
}
