// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: payment.proto

package server

import (
	"context"

	"gomall/service/payment/rpc/internal/logic"
	"gomall/service/payment/rpc/internal/svc"
	"gomall/service/payment/rpc/types/payment"
)

type PaymentServiceServer struct {
	svcCtx *svc.ServiceContext
	payment.UnimplementedPaymentServiceServer
}

func NewPaymentServiceServer(svcCtx *svc.ServiceContext) *PaymentServiceServer {
	return &PaymentServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PaymentServiceServer) Charge(ctx context.Context, in *payment.ChargeReq) (*payment.ChargeResp, error) {
	l := logic.NewChargeLogic(ctx, s.svcCtx)
	return l.Charge(in)
}

func (s *PaymentServiceServer) CancelPayment(ctx context.Context, in *payment.CancelPaymentReq) (*payment.CancelPaymentResp, error) {
	l := logic.NewCancelPaymentLogic(ctx, s.svcCtx)
	return l.CancelPayment(in)
}

func (s *PaymentServiceServer) QueryPayment(ctx context.Context, in *payment.QueryPaymentReq) (*payment.QueryPaymentResp, error) {
	l := logic.NewQueryPaymentLogic(ctx, s.svcCtx)
	return l.QueryPayment(in)
}
