// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type AddItemRequest struct {
	CartItem CartItem `json:"cart_item"`
}

type AddItemResponse struct {
	Success bool `json:"success"`
}

type CartItem struct {
	ProductId uint32 `json:"product_id"`
	Quantity  int32  `json:"quantity"`
}

type EmptyCartRequest struct {
}

type EmptyCartResponse struct {
	Success bool `json:"success"`
}

type GetCartRequest struct {
}

type GetCartResponse struct {
	UserId    uint32     `json:"user_id"`
	CartItems []CartItem `json:"cart_items"`
}
