Name: product.rpc
ListenOn: 0.0.0.0:9001
Etcd:
  Hosts:
  - etcd:2379
  Key: product.rpc
  User: root
  Pass: "123456"

Mysql:
  DataSource: root:aiwass@tcp(mysql:3306)/go_mall?charset=utf8mb4&parseTime=True&loc=Local

RedisConfig:
  Host: redis:6379
  Password:
  DB: 0
  PoolSize: 20

Prometheus:
  Host: 0.0.0.0
  Port: 9091
  Path: /metrics