// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"gomall/service/order/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/order/list-orders",
					Handler: ListOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/order/place-order",
					Handler: PlaceOrderHandler(serverCtx),
				},
			}...,
		),
	)
}
