// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type CreateRequest struct {
	Name       string   `json:"name"`
	Desc       string   `json:"desc"`
	Stock      int64    `json:"stock"`
	Price      int64    `json:"price"`
	Status     int64    `json:"status"`
	Picture    string   `json:"picture"`
	Categories []string `json:"categories"`
}

type CreateResponse struct {
	Id uint32 `json:"id"`
}

type DetailRequest struct {
	Id uint32 `json:"id"`
}

type DetailResponse struct {
	Id         uint32   `json:"id"`
	Name       string   `json:"name"`
	Desc       string   `json:"desc"`
	Stock      int64    `json:"stock"`
	Price      int64    `json:"price"`
	Status     int64    `json:"status"`
	Picture    string   `json:"picture"`
	Categories []string `json:"categories"`
}

type ListProductRequest struct {
	Page         int32  `json:"page"`
	PageSize     int64  `json:"page_size"`
	CategoryName string `json:"category_name"`
}

type ListProductResponse struct {
	ProductList []*Product `json:"product_list"`
}

type Product struct {
	Id         uint32   `json:"id"`
	Name       string   `json:"name"`
	Desc       string   `json:"desc"`
	Price      int64    `json:"price"`
	Picture    string   `json:"picture"`
	Categories []string `json:"categories"`
}

type RemoveRequest struct {
	Id uint32 `json:"id"`
}

type RemoveResponse struct {
	Success bool `json:"success"`
}

type UpdateRequest struct {
	Id         uint32   `json:"id"`
	Name       string   `json:"name,optional"`
	Desc       string   `json:"desc,optional"`
	Stock      int64    `json:"stock"`
	Price      int64    `json:"price,optional"`
	Status     int64    `json:"status,optional"`
	Picture    string   `json:"picture,optional"`
	Categories []string `json:"categories"`
}

type UpdateResponse struct {
	Success bool `json:"success"`
}
