// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type Address struct {
	StreetAddress string `json:"street_address"`
	City          string `json:"city"`
	State         string `json:"state"`
	Country       string `json:"country"`
	ZipCode       int32  `json:"zip_code"`
}

type CartItem struct {
	ProductId uint32 `json:"product_id"`
	Quantity  int32  `json:"quantity"`
}

type CheckoutRequest struct {
	Currency    string     `json:"currency"`
	Firstname   string     `json:"firstname"`
	Lastname    string     `json:"lastname"`
	Email       string     `json:"email"`
	UserAddress Address    `json:"user_address"`
	CardInfo    CreditCard `json:"credit_card"`
	CartItems   []CartItem `json:"cart_items"`
}

type CheckoutResponse struct {
	OrderId       string `json:"order_id"`
	TransactionId string `json:"transaction_id"`
}

type CreditCard struct {
	CreditCardNumber          string `json:"credit_card_number"`
	CreditCardCVV             int32  `json:"credit_card_cvv"`
	CreditCardExpirationYear  int32  `json:"credit_card_expiration_year"`
	CreditCardExpirationMonth int32  `json:"credit_card_expiration_month"`
}
