// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: checkout.proto

package server

import (
	"context"

	"gomall/service/checkout/rpc/internal/logic"
	"gomall/service/checkout/rpc/internal/svc"
	"gomall/service/checkout/rpc/types/checkout"
)

type CheckoutServiceServer struct {
	svcCtx *svc.ServiceContext
	checkout.UnimplementedCheckoutServiceServer
}

func NewCheckoutServiceServer(svcCtx *svc.ServiceContext) *CheckoutServiceServer {
	return &CheckoutServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CheckoutServiceServer) Checkout(ctx context.Context, in *checkout.CheckoutReq) (*checkout.CheckoutResp, error) {
	l := logic.NewCheckoutLogic(ctx, s.svcCtx)
	return l.Checkout(in)
}
