// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"gomall/service/cart/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/cart/add-item",
					Handler: AddItemHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/cart/empty-cart",
					Handler: EmptyCartHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cart/get-cart",
					Handler: GetCartHandler(serverCtx),
				},
			}...,
		),
	)
}
