// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package types

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type LogoutRequest struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	UserId       uint32 `json:"userId"`
}

type LogoutResponse struct {
	Res bool `json:"res"`
}

type RefreshAccessTokenRequest struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type RefreshAccessTokenResponse struct {
	AccessToken string `json:"accessToken"`
}

type RegisterRequest struct {
	Email           string `json:"email"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirmPassword"`
}

type RegisterResponse struct {
	Id uint32 `json:"id"`
}

type UserInfoResponse struct {
	Id uint32 `json:"id"`
}

type VerifyAccessTokenRequest struct {
	AccessToken string `json:"accessToken"`
	UserId      uint32 `json:"userId"`
}

type VerifyAccessTokenResponse struct {
	Res bool `json:"res"`
}
